##Function by NOPEname

scoreboard players set @s[score_aim.y_min=1,score_aim.y=2] rrx 1
scoreboard players set @s[score_aim.y_min=3,score_aim.y=4] rrx 2
scoreboard players set @s[score_aim.y_min=5,score_aim.y=5] rrx 3
scoreboard players set @s[score_aim.y_min=6,score_aim.y=7] rrx 4
scoreboard players set @s[score_aim.y_min=8,score_aim.y=9] rrx 5
scoreboard players set @s[score_aim.y_min=10,score_aim.y=11] rrx 6
scoreboard players set @s[score_aim.y_min=12,score_aim.y=12] rrx 7
scoreboard players set @s[score_aim.y_min=13,score_aim.y=14] rrx 8
scoreboard players set @s[score_aim.y_min=15,score_aim.y=16] rrx 9
scoreboard players set @s[score_aim.y_min=17,score_aim.y=18] rrx 10
scoreboard players set @s[score_aim.y_min=19,score_aim.y=19] rrx 11
scoreboard players set @s[score_aim.y_min=20,score_aim.y=21] rrx 12
scoreboard players set @s[score_aim.y_min=22,score_aim.y=23] rrx 13
scoreboard players set @s[score_aim.y_min=24,score_aim.y=25] rrx 14
scoreboard players set @s[score_aim.y_min=26,score_aim.y=26] rrx 15
scoreboard players set @s[score_aim.y_min=27,score_aim.y=28] rrx 16
scoreboard players set @s[score_aim.y_min=29,score_aim.y=30] rrx 17
scoreboard players set @s[score_aim.y_min=31,score_aim.y=32] rrx 18
scoreboard players set @s[score_aim.y_min=33,score_aim.y=33] rrx 19
scoreboard players set @s[score_aim.y_min=34,score_aim.y=35] rrx 20
scoreboard players set @s[score_aim.y_min=36,score_aim.y=37] rrx 21
scoreboard players set @s[score_aim.y_min=38,score_aim.y=39] rrx 22
scoreboard players set @s[score_aim.y_min=40,score_aim.y=40] rrx 23
scoreboard players set @s[score_aim.y_min=41,score_aim.y=42] rrx 24
scoreboard players set @s[score_aim.y_min=43,score_aim.y=44] rrx 25
scoreboard players set @s[score_aim.y_min=45,score_aim.y=46] rrx 26
scoreboard players set @s[score_aim.y_min=47,score_aim.y=47] rrx 27
scoreboard players set @s[score_aim.y_min=48,score_aim.y=49] rrx 28
scoreboard players set @s[score_aim.y_min=50,score_aim.y=51] rrx 29
scoreboard players set @s[score_aim.y_min=52,score_aim.y=53] rrx 30
scoreboard players set @s[score_aim.y_min=54,score_aim.y=54] rrx 31
scoreboard players set @s[score_aim.y_min=55,score_aim.y=56] rrx 32
scoreboard players set @s[score_aim.y_min=57,score_aim.y=58] rrx 33
scoreboard players set @s[score_aim.y_min=59,score_aim.y=60] rrx 34
scoreboard players set @s[score_aim.y_min=61,score_aim.y=61] rrx 35
scoreboard players set @s[score_aim.y_min=62,score_aim.y=63] rrx 36
scoreboard players set @s[score_aim.y_min=64,score_aim.y=65] rrx 37
scoreboard players set @s[score_aim.y_min=66,score_aim.y=67] rrx 38
scoreboard players set @s[score_aim.y_min=68,score_aim.y=68] rrx 39
scoreboard players set @s[score_aim.y_min=69,score_aim.y=70] rrx 40
scoreboard players set @s[score_aim.y_min=71,score_aim.y=72] rrx 41
scoreboard players set @s[score_aim.y_min=73,score_aim.y=74] rrx 42
scoreboard players set @s[score_aim.y_min=75,score_aim.y=75] rrx 43
scoreboard players set @s[score_aim.y_min=76,score_aim.y=77] rrx 44
scoreboard players set @s[score_aim.y_min=78,score_aim.y=79] rrx 45
scoreboard players set @s[score_aim.y_min=80,score_aim.y=81] rrx 46
scoreboard players set @s[score_aim.y_min=82,score_aim.y=82] rrx 47
scoreboard players set @s[score_aim.y_min=83,score_aim.y=84] rrx 48
scoreboard players set @s[score_aim.y_min=85,score_aim.y=86] rrx 49
scoreboard players set @s[score_aim.y_min=87,score_aim.y=88] rrx 50
scoreboard players set @s[score_aim.y_min=89,score_aim.y=90] rrx 51
scoreboard players set @s[score_aim.y_min=91,score_aim.y=91] rrx 52
scoreboard players set @s[score_aim.y_min=92,score_aim.y=93] rrx 53
scoreboard players set @s[score_aim.y_min=94,score_aim.y=95] rrx 54
scoreboard players set @s[score_aim.y_min=96,score_aim.y=97] rrx 55
scoreboard players set @s[score_aim.y_min=98,score_aim.y=98] rrx 56
scoreboard players set @s[score_aim.y_min=99,score_aim.y=100] rrx 57
scoreboard players set @s[score_aim.y_min=101,score_aim.y=102] rrx 58
scoreboard players set @s[score_aim.y_min=103,score_aim.y=104] rrx 59
scoreboard players set @s[score_aim.y_min=105,score_aim.y=105] rrx 60
scoreboard players set @s[score_aim.y_min=106,score_aim.y=107] rrx 61
scoreboard players set @s[score_aim.y_min=108,score_aim.y=109] rrx 62
scoreboard players set @s[score_aim.y_min=110,score_aim.y=111] rrx 63
scoreboard players set @s[score_aim.y_min=112,score_aim.y=112] rrx 64
scoreboard players set @s[score_aim.y_min=113,score_aim.y=114] rrx 65
scoreboard players set @s[score_aim.y_min=115,score_aim.y=116] rrx 66
scoreboard players set @s[score_aim.y_min=117,score_aim.y=118] rrx 67
scoreboard players set @s[score_aim.y_min=119,score_aim.y=120] rrx 68
scoreboard players set @s[score_aim.y_min=121,score_aim.y=121] rrx 69
scoreboard players set @s[score_aim.y_min=122,score_aim.y=123] rrx 70
scoreboard players set @s[score_aim.y_min=124,score_aim.y=125] rrx 71
scoreboard players set @s[score_aim.y_min=126,score_aim.y=127] rrx 72
scoreboard players set @s[score_aim.y_min=128,score_aim.y=128] rrx 73
scoreboard players set @s[score_aim.y_min=129,score_aim.y=130] rrx 74
scoreboard players set @s[score_aim.y_min=131,score_aim.y=132] rrx 75
scoreboard players set @s[score_aim.y_min=133,score_aim.y=134] rrx 76
scoreboard players set @s[score_aim.y_min=135,score_aim.y=135] rrx 77
scoreboard players set @s[score_aim.y_min=136,score_aim.y=137] rrx 78
scoreboard players set @s[score_aim.y_min=138,score_aim.y=139] rrx 79
scoreboard players set @s[score_aim.y_min=140,score_aim.y=141] rrx 80
scoreboard players set @s[score_aim.y_min=142,score_aim.y=143] rrx 81
scoreboard players set @s[score_aim.y_min=144,score_aim.y=144] rrx 82
scoreboard players set @s[score_aim.y_min=145,score_aim.y=146] rrx 83
scoreboard players set @s[score_aim.y_min=147,score_aim.y=148] rrx 84
scoreboard players set @s[score_aim.y_min=149,score_aim.y=150] rrx 85
scoreboard players set @s[score_aim.y_min=151,score_aim.y=152] rrx 86
scoreboard players set @s[score_aim.y_min=153,score_aim.y=153] rrx 87
scoreboard players set @s[score_aim.y_min=154,score_aim.y=155] rrx 88
scoreboard players set @s[score_aim.y_min=156,score_aim.y=157] rrx 89
scoreboard players set @s[score_aim.y_min=158,score_aim.y=159] rrx 90
scoreboard players set @s[score_aim.y_min=160,score_aim.y=160] rrx 91
scoreboard players set @s[score_aim.y_min=161,score_aim.y=162] rrx 92
scoreboard players set @s[score_aim.y_min=163,score_aim.y=164] rrx 93
scoreboard players set @s[score_aim.y_min=165,score_aim.y=166] rrx 94
scoreboard players set @s[score_aim.y_min=167,score_aim.y=168] rrx 95
scoreboard players set @s[score_aim.y_min=169,score_aim.y=169] rrx 96
scoreboard players set @s[score_aim.y_min=170,score_aim.y=171] rrx 97
scoreboard players set @s[score_aim.y_min=172,score_aim.y=173] rrx 98
scoreboard players set @s[score_aim.y_min=174,score_aim.y=175] rrx 99
scoreboard players set @s[score_aim.y_min=176,score_aim.y=177] rrx 100
