##Function by NOPEname

scoreboard players set @s[score_aim.z_min=1,score_aim.z=2] rry 1
scoreboard players set @s[score_aim.z_min=3,score_aim.z=4] rry 2
scoreboard players set @s[score_aim.z_min=5,score_aim.z=5] rry 3
scoreboard players set @s[score_aim.z_min=6,score_aim.z=7] rry 4
scoreboard players set @s[score_aim.z_min=8,score_aim.z=9] rry 5
scoreboard players set @s[score_aim.z_min=10,score_aim.z=11] rry 6
scoreboard players set @s[score_aim.z_min=12,score_aim.z=12] rry 7
scoreboard players set @s[score_aim.z_min=13,score_aim.z=14] rry 8
scoreboard players set @s[score_aim.z_min=15,score_aim.z=16] rry 9
scoreboard players set @s[score_aim.z_min=17,score_aim.z=18] rry 10
scoreboard players set @s[score_aim.z_min=19,score_aim.z=19] rry 11
scoreboard players set @s[score_aim.z_min=20,score_aim.z=21] rry 12
scoreboard players set @s[score_aim.z_min=22,score_aim.z=23] rry 13
scoreboard players set @s[score_aim.z_min=24,score_aim.z=25] rry 14
scoreboard players set @s[score_aim.z_min=26,score_aim.z=26] rry 15
scoreboard players set @s[score_aim.z_min=27,score_aim.z=28] rry 16
scoreboard players set @s[score_aim.z_min=29,score_aim.z=30] rry 17
scoreboard players set @s[score_aim.z_min=31,score_aim.z=32] rry 18
scoreboard players set @s[score_aim.z_min=33,score_aim.z=33] rry 19
scoreboard players set @s[score_aim.z_min=34,score_aim.z=35] rry 20
scoreboard players set @s[score_aim.z_min=36,score_aim.z=37] rry 21
scoreboard players set @s[score_aim.z_min=38,score_aim.z=39] rry 22
scoreboard players set @s[score_aim.z_min=40,score_aim.z=40] rry 23
scoreboard players set @s[score_aim.z_min=41,score_aim.z=42] rry 24
scoreboard players set @s[score_aim.z_min=43,score_aim.z=44] rry 25
scoreboard players set @s[score_aim.z_min=45,score_aim.z=46] rry 26
scoreboard players set @s[score_aim.z_min=47,score_aim.z=47] rry 27
scoreboard players set @s[score_aim.z_min=48,score_aim.z=49] rry 28
scoreboard players set @s[score_aim.z_min=50,score_aim.z=51] rry 29
scoreboard players set @s[score_aim.z_min=52,score_aim.z=53] rry 30
scoreboard players set @s[score_aim.z_min=54,score_aim.z=54] rry 31
scoreboard players set @s[score_aim.z_min=55,score_aim.z=56] rry 32
scoreboard players set @s[score_aim.z_min=57,score_aim.z=58] rry 33
scoreboard players set @s[score_aim.z_min=59,score_aim.z=60] rry 34
scoreboard players set @s[score_aim.z_min=61,score_aim.z=61] rry 35
scoreboard players set @s[score_aim.z_min=62,score_aim.z=63] rry 36
scoreboard players set @s[score_aim.z_min=64,score_aim.z=65] rry 37
scoreboard players set @s[score_aim.z_min=66,score_aim.z=67] rry 38
scoreboard players set @s[score_aim.z_min=68,score_aim.z=68] rry 39
scoreboard players set @s[score_aim.z_min=69,score_aim.z=70] rry 40
scoreboard players set @s[score_aim.z_min=71,score_aim.z=72] rry 41
scoreboard players set @s[score_aim.z_min=73,score_aim.z=74] rry 42
scoreboard players set @s[score_aim.z_min=75,score_aim.z=75] rry 43
scoreboard players set @s[score_aim.z_min=76,score_aim.z=77] rry 44
scoreboard players set @s[score_aim.z_min=78,score_aim.z=79] rry 45
scoreboard players set @s[score_aim.z_min=80,score_aim.z=81] rry 46
scoreboard players set @s[score_aim.z_min=82,score_aim.z=82] rry 47
scoreboard players set @s[score_aim.z_min=83,score_aim.z=84] rry 48
scoreboard players set @s[score_aim.z_min=85,score_aim.z=86] rry 49
scoreboard players set @s[score_aim.z_min=87,score_aim.z=88] rry 50
scoreboard players set @s[score_aim.z_min=89,score_aim.z=90] rry 51
scoreboard players set @s[score_aim.z_min=91,score_aim.z=91] rry 52
scoreboard players set @s[score_aim.z_min=92,score_aim.z=93] rry 53
scoreboard players set @s[score_aim.z_min=94,score_aim.z=95] rry 54
scoreboard players set @s[score_aim.z_min=96,score_aim.z=97] rry 55
scoreboard players set @s[score_aim.z_min=98,score_aim.z=98] rry 56
scoreboard players set @s[score_aim.z_min=99,score_aim.z=100] rry 57
scoreboard players set @s[score_aim.z_min=101,score_aim.z=102] rry 58
scoreboard players set @s[score_aim.z_min=103,score_aim.z=104] rry 59
scoreboard players set @s[score_aim.z_min=105,score_aim.z=105] rry 60
scoreboard players set @s[score_aim.z_min=106,score_aim.z=107] rry 61
scoreboard players set @s[score_aim.z_min=108,score_aim.z=109] rry 62
scoreboard players set @s[score_aim.z_min=110,score_aim.z=111] rry 63
scoreboard players set @s[score_aim.z_min=112,score_aim.z=112] rry 64
scoreboard players set @s[score_aim.z_min=113,score_aim.z=114] rry 65
scoreboard players set @s[score_aim.z_min=115,score_aim.z=116] rry 66
scoreboard players set @s[score_aim.z_min=117,score_aim.z=118] rry 67
scoreboard players set @s[score_aim.z_min=119,score_aim.z=120] rry 68
scoreboard players set @s[score_aim.z_min=121,score_aim.z=121] rry 69
scoreboard players set @s[score_aim.z_min=122,score_aim.z=123] rry 70
scoreboard players set @s[score_aim.z_min=124,score_aim.z=125] rry 71
scoreboard players set @s[score_aim.z_min=126,score_aim.z=127] rry 72
scoreboard players set @s[score_aim.z_min=128,score_aim.z=128] rry 73
scoreboard players set @s[score_aim.z_min=129,score_aim.z=130] rry 74
scoreboard players set @s[score_aim.z_min=131,score_aim.z=132] rry 75
scoreboard players set @s[score_aim.z_min=133,score_aim.z=134] rry 76
scoreboard players set @s[score_aim.z_min=135,score_aim.z=135] rry 77
scoreboard players set @s[score_aim.z_min=136,score_aim.z=137] rry 78
scoreboard players set @s[score_aim.z_min=138,score_aim.z=139] rry 79
scoreboard players set @s[score_aim.z_min=140,score_aim.z=141] rry 80
scoreboard players set @s[score_aim.z_min=142,score_aim.z=143] rry 81
scoreboard players set @s[score_aim.z_min=144,score_aim.z=144] rry 82
scoreboard players set @s[score_aim.z_min=145,score_aim.z=146] rry 83
scoreboard players set @s[score_aim.z_min=147,score_aim.z=148] rry 84
scoreboard players set @s[score_aim.z_min=149,score_aim.z=150] rry 85
scoreboard players set @s[score_aim.z_min=151,score_aim.z=152] rry 86
scoreboard players set @s[score_aim.z_min=153,score_aim.z=153] rry 87
scoreboard players set @s[score_aim.z_min=154,score_aim.z=155] rry 88
scoreboard players set @s[score_aim.z_min=156,score_aim.z=157] rry 89
scoreboard players set @s[score_aim.z_min=158,score_aim.z=159] rry 90
scoreboard players set @s[score_aim.z_min=160,score_aim.z=160] rry 91
scoreboard players set @s[score_aim.z_min=161,score_aim.z=162] rry 92
scoreboard players set @s[score_aim.z_min=163,score_aim.z=164] rry 93
scoreboard players set @s[score_aim.z_min=165,score_aim.z=166] rry 94
scoreboard players set @s[score_aim.z_min=167,score_aim.z=168] rry 95
scoreboard players set @s[score_aim.z_min=169,score_aim.z=169] rry 96
scoreboard players set @s[score_aim.z_min=170,score_aim.z=171] rry 97
scoreboard players set @s[score_aim.z_min=172,score_aim.z=173] rry 98
scoreboard players set @s[score_aim.z_min=174,score_aim.z=175] rry 99
scoreboard players set @s[score_aim.z_min=176,score_aim.z=177] rry 100
